"""Run the deliverable demo scenarios against the live LLM and write real
transcripts to examples/.

Usage:  python scripts/generate_examples.py
Requires the LLM endpoint (Ollama by default) to be up and the DB seeded.
"""

from __future__ import annotations

import json
import sys
import uuid
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.graph.build import build_graph, chat_turn

EXAMPLES_DIR = Path(__file__).resolve().parent.parent / "examples"

SCENARIOS = {
    "01_multi_turn_medical_to_booking.md": {
        "title": "Multi-turn medical conversation ending in a booking (English)",
        "turns": [
            "I've been having a severe headache and fever for two days, what should I do?",
            "It gets worse when I look at bright light, is that serious?",
            "Yes, please book me an appointment",
            "Dr. Sarah please, the Cairo branch works for me",
            "yes, confirm it",
        ],
    },
    "02_arabic_medical_conversation.md": {
        "title": "Multi-turn medical conversation ending in a booking (Arabic)",
        "turns": [
            "عندي ألم في الصدر من الصباح وأحس بضيق في التنفس",
            "الألم مش مستمر، بييجي وبيروح",
            "طيب احجزلي موعد مع دكتورة منى عادل في الإسكندرية",
            "اه تمام",
        ],
    },
    "03_data_lookups.md": {
        "title": "Hospital data lookups (doctors, specializations, branches)",
        "turns": [
            "Who are the cardiologists at the Riyadh branch?",
            "What specializations are available at the Alexandria branch?",
            "ما هي فروع المستشفى؟",
        ],
    },
    "05_booking_management.md": {
        "title": "Managing bookings: book, list, cancel (persisted records)",
        "turns": [
            "I want to book an appointment with Dr. Khalid Al-Mansouri",
            "yes",
            "Show me my bookings",
            "Please cancel my booking",
            "Show me my bookings again",
        ],
    },
    "06_same_name_disambiguation.md": {
        "title": "Same-name doctors: branch disambiguation (never-guess)",
        "turns": [
            "I'd like to book with Dr. Layla in cardiology",
            "the Riyadh branch please",
            "yes",
        ],
    },
}


def main() -> None:
    if sys.platform == "win32":
        sys.stdout.reconfigure(encoding="utf-8")
    EXAMPLES_DIR.mkdir(exist_ok=True)
    graph = build_graph()

    for filename, scenario in SCENARIOS.items():
        thread_id = str(uuid.uuid4())
        lines = [f"# {scenario['title']}", "", "> Generated by `scripts/generate_examples.py` against the live system.", ""]
        print(f"--- {scenario['title']} ---")
        for turn in scenario["turns"]:
            response = chat_turn(graph, thread_id, turn)
            payload = json.dumps(response, ensure_ascii=False, indent=2)
            print(f"User: {turn}\n{payload}\n")
            lines += [f"**User:** {turn}", "", "**Chatbot:**", "", "```json", payload, "```", ""]
        (EXAMPLES_DIR / filename).write_text("\n".join(lines), encoding="utf-8")
        print(f"Wrote examples/{filename}\n")


if __name__ == "__main__":
    main()
